import type { NextPage, GetStaticProps, GetStaticPaths } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { createServerSideHelpers } from "@trpc/react-query/server";
import { appRouter } from "~/server/api/root";
import { prisma } from "~/server/db";
import superjson from "superjson";
import { PageLayout } from "~/components/Layout";
import Image from "next/image";

const ProfilePage: NextPage<{ username: string }> = ({ username }) => {
  const { data } = api.profile.getUserByUsername.useQuery({
    username: username,
  });

  if (!data) return <div>Something went wrong</div>;
  return (
    <>
      <Head>
        <title>{data.username}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="relative h-48 border-b border-slate-600 bg-gradient-to-r from-teal-200 to-teal-500">
          <div className="absolute bottom-0 left-0 -mb-24 ml-8 flex flex-col items-center">
            <Image
              src={data.profileImageUrl}
              alt={`${data.username ?? ""}'s profile picture`}
              width={128}
              height={128}
              className="mb-2 rounded-full border-4 border-black"
            />
            <div className="text-xl font-semibold">
              <p>{`@${data.username ?? ""}`}</p>
            </div>
          </div>
          <div className="h-80"></div>
          <div className="w-full border-b border-slate-600"></div>
        </div>
      </PageLayout>
    </>
  );
};

export default ProfilePage;

export const getStaticProps: GetStaticProps = async (ctx) => {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: { prisma, userId: null },
    transformer: superjson,
  });

  const slug = ctx.params?.slug;

  if (typeof slug !== "string") throw new Error("slug not found");
  const username = slug.replace("@", "");

  await helpers.profile.getUserByUsername.prefetch({ username: username });

  return {
    props: {
      trpcState: helpers.dehydrate(),
      username,
    },
  };
};

export const getStaticPaths: GetStaticPaths = () => {
  return { paths: [], fallback: "blocking" };
};
