name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URl: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts"

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "VAR_NAME=${{ secrets.DATABASE_URL }}" >> .env

      - name: Type check
        env:
          ENV_FILE: .env
        run: npm run typecheck

      - name: Lint
        env:
          ENV_FILE: .env
        run: npm run lint
